<?php
    $this->title = "Home";
    $this->headTitle($this->title);
?>
<div id="header">
            <h1>Nama Yagja 2011</h1>
            <p>&nbsp;</p>
</div><!-- header -->
<div id="sidebar">
    <p>Dear devotees of the  Divine Couple, please accept our dandavats, greetings and blessings!</p>
    <p>The Janmastami  celebration approaches and this is one of the greatest opportunities to  celebrate divinity with loving offerings. The best sacrificial offering in  Kali-yuga is the Holy Name that not only liberates from material entanglement  and purifies the heart completely but also satisfies the Supreme Lord Sri  Krsna, His beloved companions, Srimati Radhika and Her friends, and also all  the devotees around the globe and universe.</p>
    <p>This year again we  organize a grand international nama-yajna offering on the occasion of the next  Janmastami to commemorate the event. The offering period will be from <strong>/ezt még nem tudom/.</strong> You are also  invited to join our spiritual sangha, bridging continents, missions, hearts and  souls. </p>
    <p>Please register and if  we are more and more we can also raise the number of mantras offered to the  Divine Couple. </p>
    <p>Let’s be united in  divine service! </p>
    <p>&nbsp;</p>
    <p><br />
    Hungarian Vaishnava  Hindu Mission</p>
</div><!-- sidebar -->

<div id="mainContainer">

<?php echo "<p><img src='{$this->baseUrl()}/assets/japamala.jpg' width='500' height='333' alt='japamala' longdesc='assets/japamala.jpg' /></p>"; ?>


<table width="600" border="1" cellspacing="5" cellpadding="5">

  <tr>
    <th scope="row">&nbsp;</th>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <th scope="row">&nbsp;</th>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <th scope="row">&nbsp;</th>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <th scope="row">&nbsp;</th>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <th scope="row">&nbsp;</th>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <th scope="row">&nbsp;</th>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <th scope="row">&nbsp;</th>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <th scope="row">&nbsp;</th>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <th scope="row">&nbsp;</th>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <th scope="row">&nbsp;</th>
    <td>&nbsp;</td>
  </tr>
</table>

<p>&nbsp;</p>
</div><!-- mainContainer -->