<?php
    $this->title = "Registration";
    $this->headTitle($this->title);
?>  
<div id="header">
    <h1>Nama Yajna 2011</h1>
    <blockquote>
      <h3>Registration</h3>
    </blockquote>
  </div><!-- header -->
<div id="sidebar">
    <p>The holy name of Krsna cleanses the mirror  of the heart<br />
and forever extinguishes the fire of  misery,<br />
that great conflagration in the forest of  birth and death.</p>
    <p>As the evening  lotus blooms in the moon’s cooling rays,<br />
      the heart begins to blossom in the nectar  of the name.</p>
    <p>And at last the soul awakens to its real  inner treasure –<br />
      a life of unconditional surrender for  Krsna’s sweetest pleasure.</p>
    <p>/Siksastakam/</p>
<p>&nbsp;</p>
</div><!-- sidebar -->
<div id="mainContainer">

    <?php echo $this->form ; ?>
    
</div><!-- mainContainer -->