<?php
    $this->title = "Testemonials";
    $this->headTitle($this->title);
?>
<div id="header">
    <h1>Nama Yajna 2011</h1>
    <blockquote>
      <h3>Testemonials/feedbacks</h3>
    </blockquote>
<p>&nbsp;</p>
  </div>
<div id="sidebar">
    <p>Thank you very much for this beautiful  service.<br />
Haribol, dandavats!<br />
Your Krsna priya devi dasi (Bulgaria)</p>
    <p>We will gladly take part in this Jajna.<br />
      Natasha (Ukraine)</p>
    <p>Radhe Radhe I will join, thank you. Krsna  bless you.<br />
      Kalavati (Bosnia)</p>
    <p>Guru Maharaja lelkesen fogadta ezt a  kezdeményezést. Guru Maharajával  a  tanítványok a fülöpjakabi GOPI SÉVA ASHRAMBAN Krisna-Janmastami napján  egésznapos NÁMA-SÉVÁ-t fogunk tartani, így lélekben valamennyien együtt leszünk.<br />
      Guru Maharaja küldi áldásait és  jókívánságait minden  õszinte bhakta felé.<br />
      Narajan dász</p>
    <p>I am very honoured and happy to be invitet  to your celebration of the offering the unlimited numbers of the holy names for  Janmasthami this year, and I would like to join very much.<br />
      Your servant bhn. ljerka (Croatia)</p>
    <p>Kivanom, hogy sikeruljon ez a szep  felajanlas es mindenki legyen Tole boldog!<br />
      Dandavat! Syam </p>
    <p>Thank you for forwarding your Gurudeva's  letter to me. Nice way to encourage us to worship Sri Krishna on His Holy  advent day by chanting Hare Krishna Mahamantra for His pleasure.<br />
      ys, Madan Gopal Das (Slovenia)</p>
    <p>Hare Krishna<br />
      We were discussing this invitation and we  are happy that this offering to our beloved Sri Krishnaji is to be made on his  appearance day. In heart we will be with you.<br />
      Radhe Radhe<br />
      nnd (Croatia)</p>
    <p>Haribol!<br />
      We will be with You with hearts and souls!<br />
      Daruka dasa family from Istria</p>
    <p>Nagyon jó volt ebben részt venni, szívesen  csatlakozunk hozzá ismét jövõre is. <br />
      Ísvarí d.d.    </p>
    <p>&nbsp;</p>
    <p>&nbsp;</p>
    <p>&nbsp;</p>
</div><!-- sidebar -->
<div id="mainContainer">

    <?php echo "<p><img src='{$this->baseUrl()}/assets/japamala.jpg' width='500' height='333' alt='japamala' longdesc='assets/japamala.jpg' /></p>"; ?>
    <h3><strong>Nama Yajna 2010</strong></h3>
    <p>&quot;Dear swamis, prabhus,  matas, friends, brothers and sisters!<br />
    Please accept my  humble dandavats after completing this beautiful offering of congregational  chanting of the Holy Names of the Lord Sri Krsna as a birthday gift.</p>
    <p>We all had a very  special period of a month’s time celebration – from the holy appearance day of  Balaram dauji up until the appearance of Sriamti Radhika, the Divine consort,  including in the middle section the appearance of Sri Krsna, reality the  beautiful.<br />
      That is the period to  celebrate the presence of the Divine productive power (Balaram), the supreme  consciousness (Vasudev Krsna) and the power of creativity, beauty, harmony and  love (Srimati Radhika).<br />
      Thank you for  participating in our humble offering, with your contribution it has become a grand  victory of the Holy Name all over the earth. I wish to express my special  thanks and gratitude to all those who diligently and relentlessly helped to  organize this spiritual sangha, to keep the fire of dedication alive in all of  us, and to invite more and more participants. I wish all good blessings shower  on them! We did not mention by name the hundreds of devotees and friends who  took part in our offering, be blessed also!</p>
    <table border="1" cellspacing="0" cellpadding="0" width="100%">
      <tr>
        <td width="63%" valign="top"><p><strong>Country</strong></p></td>
        <td width="32%" valign="top"><p align="right"><strong>Registered rounds</strong></p></td>
        <td width="3%" valign="top"><p><strong>&nbsp;</strong></p></td>
      </tr>
      <tr>
        <td width="63%" valign="top"><p>&nbsp;</p></td>
        <td width="32%" valign="top"><p align="right">&nbsp;</p></td>
        <td width="3%" valign="top"><p>&nbsp;</p></td>
      </tr>
      <tr>
        <td width="63%" valign="top"><p>Australia </p></td>
        <td width="32%" valign="top"><p align="right">1200</p></td>
        <td width="3%" valign="top"><p>&nbsp;</p></td>
      </tr>
      <tr>
        <td width="63%" valign="top"><p>Austria </p></td>
        <td width="32%" valign="top"><p align="right">16</p></td>
        <td width="3%" valign="top"><p>&nbsp;</p></td>
      </tr>
      <tr>
        <td width="63%" valign="top"><p>Bosnia&amp;Hercegovina</p></td>
        <td width="32%" valign="top"><p align="right">64</p></td>
        <td width="3%" valign="top"><p>&nbsp;</p></td>
      </tr>
      <tr>
        <td width="63%" valign="top"><p>Bulgaria Sofia yatra</p></td>
        <td width="32%" valign="top"><p align="right">1406</p></td>
        <td width="3%" valign="top"><p>&nbsp;</p></td>
      </tr>
      <tr>
        <td width="63%" valign="top"><p>Croatia </p></td>
        <td width="32%" valign="top"><p align="right">480</p></td>
        <td width="3%" valign="top"><p>&nbsp;</p></td>
      </tr>
      <tr>
        <td width="63%" valign="top"><p>Czech Republic </p></td>
        <td width="32%" valign="top"><p align="right">32</p></td>
        <td width="3%" valign="top"><p>&nbsp;</p></td>
      </tr>
      <tr>
        <td width="63%" valign="top"><p>Germany </p></td>
        <td width="32%" valign="top"><p align="right">54</p></td>
        <td width="3%" valign="top"><p>&nbsp;</p></td>
      </tr>
      <tr>
        <td width="63%" valign="top"><p>Great Britain London yatra</p></td>
        <td width="32%" valign="top"><p align="right">264</p></td>
        <td width="3%" valign="top"><p>&nbsp;</p></td>
      </tr>
      <tr>
        <td width="63%" valign="top"><p><strong>Hungary</strong></p></td>
        <td width="32%" valign="top"><p align="right">&nbsp;</p></td>
        <td width="3%" valign="top"><p>&nbsp;</p></td>
      </tr>
      <tr>
        <td width="63%" valign="top"><p align="right">Hansakunda    Ashram Kecskemét</p></td>
        <td width="32%" valign="top"><p align="right">488</p></td>
        <td width="3%" valign="top"><p>&nbsp;</p></td>
      </tr>
      <tr>
        <td width="63%" valign="top"><p align="right">Sadhana    ashram Pécs</p></td>
        <td width="32%" valign="top"><p align="right">1392</p></td>
        <td width="3%" valign="top"><p>&nbsp;</p></td>
      </tr>
      <tr>
        <td width="63%" valign="top"><p align="right">Budapest Ashram</p></td>
        <td width="32%" valign="top"><p align="right">966</p></td>
        <td width="3%" valign="top"><p>&nbsp;</p></td>
      </tr>
      <tr>
        <td width="63%" valign="top"><p align="right">Nilacal    sangha Győr</p></td>
        <td width="32%" valign="top"><p align="right">432</p></td>
        <td width="3%" valign="top"><p>&nbsp;</p></td>
      </tr>
      <tr>
        <td width="63%" valign="top"><p align="right">Nandafalva Hindu     Temple    community</p></td>
        <td width="32%" valign="top"><p align="right">34</p></td>
        <td width="3%" valign="top"><p>&nbsp;</p></td>
      </tr>
      <tr>
        <td width="63%" valign="top"><p align="right">Debrecen yatra</p></td>
        <td width="32%" valign="top"><p align="right">48</p></td>
        <td width="3%" valign="top"><p>&nbsp;</p></td>
      </tr>
      <tr>
        <td width="63%" valign="top"><p align="right">Gopiseva    ashram Fülöpjakab</p></td>
        <td width="32%" valign="top"><p align="right">448</p></td>
        <td width="3%" valign="top"><p>&nbsp;</p></td>
      </tr>
      <tr>
        <td width="63%" valign="top"><p>&nbsp;</p></td>
        <td width="32%" valign="top"><p align="right">&nbsp;</p></td>
        <td width="3%" valign="top"><p>&nbsp;</p></td>
      </tr>
      <tr>
        <td width="63%" valign="top"><p>India Delhi yatra</p></td>
        <td width="32%" valign="top"><p align="right">66</p></td>
        <td width="3%" valign="top"><p>&nbsp;</p></td>
      </tr>
      <tr>
        <td width="63%" valign="top"><p>Italy </p></td>
        <td width="32%" valign="top"><p align="right">…</p></td>
        <td width="3%" valign="top"><p>&nbsp;</p></td>
      </tr>
      <tr>
        <td width="63%" valign="top"><p>Slovenia </p></td>
        <td width="32%" valign="top"><p align="right">…</p></td>
        <td width="3%" valign="top"><p>&nbsp;</p></td>
      </tr>
      <tr>
        <td width="63%" valign="top"><p>Switzerland </p></td>
        <td width="32%" valign="top"><p align="right">105</p></td>
        <td width="3%" valign="top"><p>&nbsp;</p></td>
      </tr>
      <tr>
        <td width="63%" valign="top"><p>Ukraine </p></td>
        <td width="32%" valign="top"><p align="right">186</p></td>
        <td width="3%" valign="top"><p>&nbsp;</p></td>
      </tr>
      <tr>
        <td width="63%" valign="top"><p>&nbsp;</p></td>
        <td width="32%" valign="top"><p align="right">&nbsp;</p></td>
        <td width="3%" valign="top"><p>&nbsp;</p></td>
      </tr>
      <tr>
        <td width="63%" valign="top"><p>Friends all over the world</p></td>
        <td width="32%" valign="top"><p align="right">unlimited</p></td>
        <td width="3%" valign="top"><p>&nbsp;</p></td>
      </tr>
      <tr>
        <td width="63%" valign="top"><p>&nbsp;</p></td>
        <td width="32%" valign="top"><p align="right">&nbsp;</p></td>
        <td width="3%" valign="top"><p>&nbsp;</p></td>
      </tr>
    </table>
    <p>Devotees have joined from  14 countries, and much more sanghas. The overall registered achievement is 7681  rounds, which comes close to the original plan, the 10.000 rounds. But it is  not the numbers that is important, rather the dedication, the feeling of unity  under the divine protection of the Holy Name. Devotees from different missions,  Gurudevas and sanghas – together in a grand celebration of the sankirtan  movement – is it not the dream of Caitanya Mahaprabhu coming true? </p>
    <p>Please also excuse all  delay, inconvenience or misunderstanding if any during our communication, as  this was the first occasion to organize such an event. Next year we shall try  better, provide a website for the event, registration and comments. We are  greatly pleased if you send your experience, comments and suggestions, desires.  All are welcome!<br />
      CONTACT: <a href="mailto:juditdome@yahoo.co.uk">juditdome@yahoo.co.uk</a></p>
    <p>Please keep in touch!<br />
      Thank you once again,  and please accept my humble obeisance. In the service of Sri Sri Guru and  Gauranga remains your servant,</p>
    <p>Swami Bhakti Kamala  Tirtha<br />
      Hungarian Vaishnava  Hindu Mission&quot;</p>
<p>&nbsp;</p>
</div><!-- mainContainer -->