<?php
$this->headTitle()->setSeparator(' - ');

echo $this->doctype()."\r\n"; ?>
<html xmlns='http://www.w3.org/1999/xhtml' xml:lang='en' lang='hu'>
    <head>
        <?php echo $this->headMeta()."\r\n"; ?>
        <?php echo $this->headTitle()."\r\n"; ?>
        <?php echo $this->headLink()->prependStylesheet($this->baseUrl().'/css/style.css')."\r\n"; ?>
    </head>
    <body>
        <div id="container">
          
            <?php echo $this->layout()->content; ?>
        
          <div id="navbar">
            <ul>
              <li><a href="index.html">Home</a> <a href="testimonials/index.html">Testimonials</a><a href="registrations/index.html"> Registration</a> <a href="contact/index.html">Contact Us</a></li>
            </ul>
         </div><!-- navbar -->
           <p>&nbsp;</p>
           <p>&nbsp;</p>
          <div id="footer">
            <p>copiright 2011 © HMVM - All Right Reserved</p>
          </div><!-- footer -->
        </div><!-- container -->
</body>
    
</html>